services:
 myapp:
  platform: linux/${GUEST_ARCH}
  privileged: true
  devices:
    - "/dev/fuse:/dev/fuse"
  build:
    context: .
    args:
      VOID_PLATFORM: linux/${GUEST_ARCH}
      UID: ${GUEST_UID:-1000}
      VOID_VARIANT: ${GUEST_VARIANT:-musl}
    dockerfile: Dockerfile
  command: /home/nekobox/script.sh ${GUEST_ARCH:-x86_64} ${PRIVATE_KEY:-}
  volumes:
    - ./srcpkgs:/home/nekobox/srcpkgs:rw,Z,U   # bind current directory to /app in container
  tty: true    # optional, keeps container running for interactive shell
